# Generated by Django 4.2.1 on 2023-09-09 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitevisitor', '0003_alter_userdata_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='User_Details',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='user_credential',
            new_name='user_cred',
        ),
    ]
